title: Kaleb B | Cybersecurity Portfolio
description: Cybersecurity projects, Certifications, and Tools
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
sass:
  style: compressed
